version: 2.1
jobs:
  build:
    docker:
      - image: golang:latest

    steps:
      - checkout # Lấy mã nguồn từ kho lưu trữ
      - run:
          name: Install Dependencies
          command: go get -v ./...
      - run:
          name: Run Tests
          command: go test -v ./...
